In [5]:
# imports
import pandas as pd
import numpy as np

In [205]:
# importing csv's
claims = pd.read_csv('claims.csv')
members = pd.read_csv('members.csv')

In [206]:
# Adding a claim count column to track the amount of claims for groupby purposes
claims['claim_count'] = 1

In [221]:
# Creating a new df grouping cpt codes
cpt_code_claims = claims.groupby('cpt_code').sum()

# Parsing down to only the columns needed for this calculation
cpt_code_claims = cpt_code_claims[['paid_amount', 'claim_count']]

# Adding a new cloumn tracking the average paid per claim
cpt_code_claims['average_per_claim'] = (cpt_code_claims['paid_amount']/cpt_code_claims['claim_count']).round(2)

# Sorting values by average_per_claim and returning the top 10 highest
cpt_code_claims.sort_values('average_per_claim', ascending=False).head(10)

          paid_amount  claim_count  average_per_claim
cpt_code
36512         25600.0            1            25600.0
10101         17250.6            1            17250.6
89012         15250.0            1            15250.0
00512         14000.0            1            14000.0
50255         13000.0            1            13000.0
20610         12000.0            1            12000.0
61234         10500.0            1            10500.0
43752         10200.0            1            10200.0
99217         10200.0            1            10200.0
00123        122010.0           12            10167.5

In [220]:
# Creating a new df grouping icd codes
icd_code_claims = claims.groupby('icd_code').sum()

# Parsing down to only the columns needed for this calculation
icd_code_claims = icd_code_claims[['paid_amount', 'claim_count']]

# Adding a new column tracking the average paid per claim
icd_code_claims['average_per_claim'] = (icd_code_claims['paid_amount']/icd_code_claims['claim_count']).round(2)

# Sorting values by average_per_claim and returning the top 10 
icd_code_claims.sort_values('average_per_claim', ascending=False).head(10)

          paid_amount  claim_count  average_per_claim
icd_code
K60.0         17250.6            1            17250.6
A41.9         27400.0            2            13700.0
B99.4         51000.0            4            12750.0
B44.1         25000.0            2            12500.0
B99.01        12000.0            1            12000.0
B56.1         12000.0            1            12000.0
C45.9         12000.0            1            12000.0
C20           12000.0            1            12000.0
A01.1         34260.0            3            11420.0
B20.2         11250.0            1            11250.0