In [5]:
# imports
import pandas as pd
import numpy as np

In [205]:
# importing csv's
claims = pd.read_csv('claims.csv')
members = pd.read_csv('members.csv')

In [206]:
# Adding a claim count column to track the amount of claims for groupby purposes
claims['claim_count'] = 1

In [208]:
# Creating a new df grouping cpt codes
cpt_code_claims = claims.groupby('cpt_code').sum()
# Parsing down to only the columns needed for this calculation
cpt_code_claims = cpt_code_claims[['paid_amount', 'claim_count']]

cpt_code_claims['average_per_claim'] = (cpt_code_claims['paid_amount']/cpt_code_claims['claim_count']).round(2)

In [204]:
cpt_code_claims['average_per_claim'] = (cpt_code_claims['paid_amount']/cpt_code_claims['claim_count']).round(2)
cpt_code_claims.sort_values('average_per_claim', ascending=False).head(10)

          paid_amount  claim_count  average_per_claim
cpt_code
36512         25600.0            1            25600.0
10101         17250.6            1            17250.6
89012         15250.0            1            15250.0
00512         14000.0            1            14000.0
50255         13000.0            1            13000.0
20610         12000.0            1            12000.0
61234         10500.0            1            10500.0
99217         10200.0            1            10200.0
43752         10200.0            1            10200.0
00123        122010.0           12            10167.5

In [211]:
claims.groupby('icd_code').sum()

,claim_id,member_id,provider_id,claim_date,claim_type,cpt_code,billed_amount,paid_amount,claim_count
icd_code,,,,,,,,,
A00.0,14,4,PRV00001,3/15/2023,Inpatient,10001,42000.0,4000.0,1
A01.0,2854,629,PRV00001PRV00001PRV00001PRV01234PRV12345PRV000...,3/15/20232/15/20233/15/20232/14/20233/15/20232...,OutpatientOutpatientOutpatientOutpatientInpati...,1234512345123451234500123123451234500012001230...,20820.5,17900.5,11
A01.1,409,89,PRV12345PRV00001PRV12345,11/3/20223/12/20233/12/2023,InpatientOutpatientOutpatient,001231234512345,45400.0,34260.0,3
A09.3,388,88,PRV12345PRV12345,3/15/20234/12/2023,OutpatientOutpatient,5521070201,3520.0,3180.0,2
A09.9,482,107,PRV12345PRV12345,3/12/20238/12/2023,OutpatientOutpatient,6061999213,2420.0,2000.0,2
...,...,...,...,...,...,...,...,...,...
Z79.4,203,43,PRV11111,11/2/2023,Pharmacy,54321,250.0,180.0,1
Z79.52,453,98,PRV00004,12/11/2023,Pharmacy,36457,210.0,210.0,1
Z79.898,320,71,PRV24680PRV11111,2/8/20249/8/2024,PharmacyPharmacy,0001299999,530.0,500.0,2
Z79.899,3520,769,PRV01005PRV11223PRV90005PRV00005PRV00005PRV011...,5/3/202411/3/20235/4/202411/11/20233/11/20246/...,PharmacyPharmacyPharmacyPharmacyPharmacyPharma...,000010017F99212000000101A55555990241111100000I...,1831.0,1776.0,12
Z99.89,186,39,PRV00004,11/5/2023,Pharmacy,11111,150.0,150.0,1